export type NavigationNodeSeed = {
  key: string;
  parentKey: string | null;
  title: string;
  slug: string;
  prompt: string | null;
  answerSummary: string | null;
  responseType: 'TEXT' | 'LINK';
  linkLabel: string | null;
  linkUrl: string | null;
  evidenceExcerpt: string | null;
  evidenceSource: string | null;
  displayOrder: number;
  isActive: boolean;
};

export const navigationNodeData: NavigationNodeSeed[] = [
  {
    key: 'inicio',
    parentKey: null,
    title: 'Início',
    slug: 'inicio',
    prompt: 'Olá! Qual sua dúvida?',
    answerSummary: 'Olá! Qual sua dúvida?',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 0,
    isActive: true,
  },
  {
    key: 'curso',
    parentKey: 'inicio',
    title: 'Cursos',
    slug: 'curso',
    prompt: 'Nossos cursos são:',
    answerSummary: 'Nossos cursos são:',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 0,
    isActive: true,
  },
  {
    key: 'geral',
    parentKey: 'inicio',
    title: 'Geral',
    slug: 'geral',
    prompt: 'Sobre qual assunto geral você quer saber?',
    answerSummary: 'Sobre qual assunto geral você quer saber?',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 1,
    isActive: true,
  },
  {
    key: 'curso-dsm',
    parentKey: 'curso',
    title: 'DSM',
    slug: 'curso-dsm',
    prompt: null,
    answerSummary:
      'DSM é o curso de Desenvolvimento de Software Multiplataforma. Ele forma profissionais para criar sistemas web, mobile e soluções digitais.',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 0,
    isActive: true,
  },
  {
    key: 'curso-geo',
    parentKey: 'curso',
    title: 'GEO',
    slug: 'curso-geo',
    prompt: null,
    answerSummary:
      'GEO é o curso de Geoprocessamento, voltado a mapas digitais, análise espacial, sensoriamento remoto e dados geográficos.',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 1,
    isActive: true,
  },
  {
    key: 'curso-mb',
    parentKey: 'curso',
    title: 'MB',
    slug: 'curso-mb',
    prompt: null,
    answerSummary:
      'MB é o curso de Meio Ambiente e Recursos Hídricos, com foco em sustentabilidade, gestão ambiental e preservação dos recursos naturais.',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 2,
    isActive: true,
  },
  {
    key: 'dsm-grade',
    parentKey: 'curso-dsm',
    title: 'Grade curricular DSM',
    slug: 'dsm-grade',
    prompt: null,
    answerSummary:
      'A grade de DSM inclui programação, banco de dados, engenharia de software, desenvolvimento web, mobile, cloud e projetos integradores.',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 0,
    isActive: true,
  },
  {
    key: 'dsm-duracao',
    parentKey: 'curso-dsm',
    title: 'Duração do curso DSM',
    slug: 'dsm-duracao',
    prompt: null,
    answerSummary: 'O curso de DSM tem duração de 6 semestres, totalizando 3 anos.',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 1,
    isActive: true,
  },
  {
    key: 'geo-atuacao',
    parentKey: 'curso-geo',
    title: 'Áreas de atuação GEO',
    slug: 'geo-atuacao',
    prompt: null,
    answerSummary:
      'Profissionais de GEO podem atuar com cartografia, planejamento urbano, meio ambiente, transporte, agricultura e sistemas de informação geográfica.',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 0,
    isActive: true,
  },
  {
    key: 'mb-mercado',
    parentKey: 'curso-mb',
    title: 'Mercado de trabalho MB',
    slug: 'mb-mercado',
    prompt: null,
    answerSummary:
      'A área permite atuar em empresas, órgãos públicos, consultorias ambientais, saneamento, licenciamento e projetos de conservação.',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 0,
    isActive: true,
  },
  {
    key: 'geral-horario',
    parentKey: 'geral',
    title: 'Horário de atendimento',
    slug: 'geral-horario',
    prompt: null,
    answerSummary:
      'O atendimento da unidade deve ser confirmado nos canais oficiais da Fatec Jacareí. Este protótipo usa informações simuladas.',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 0,
    isActive: true,
  },
  {
    key: 'geral-secretaria',
    parentKey: 'geral',
    title: 'Secretaria acadêmica',
    slug: 'geral-secretaria',
    prompt: null,
    answerSummary:
      'A secretaria acadêmica auxilia com matrícula, documentos, rematrícula, histórico escolar e declarações.',
    responseType: 'TEXT',
    linkLabel: null,
    linkUrl: null,
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 1,
    isActive: true,
  },
  {
    key: 'geral-localizacao',
    parentKey: 'geral',
    title: 'Localização',
    slug: 'geral-localizacao',
    prompt: null,
    answerSummary:
      'A Fatec Jacareí fica em Jacareí, SP. Em uma versão futura, este item pode exibir mapa e rotas.',
    responseType: 'LINK',
    linkLabel: 'Abrir mapa da unidade',
    linkUrl: 'https://www.google.com/maps/search/?api=1&query=Fatec+Jacare%C3%AD',
    evidenceExcerpt: null,
    evidenceSource: null,
    displayOrder: 2,
    isActive: true,
  },
];
