-- INSERT chat flow nodes
INSERT INTO chat_flow_nodes (id, bot_message) VALUES
('inicio', 'Ola! Qual sua duvida?'),
('curso', 'Nossos cursos sao:'),
('curso-dsm', 'DSM e o curso de Desenvolvimento de Software Multiplataforma. Ele forma profissionais para criar sistemas web, mobile e solucoes digitais.'),
('dsm-grade', 'A grade de DSM inclui programacao, banco de dados, engenharia de software, desenvolvimento web, mobile, cloud e projetos integradores.'),
('dsm-duracao', 'O curso de DSM tem duracao de 6 semestres, totalizando 3 anos.'),
('curso-geo', 'GEO e o curso de Geoprocessamento, voltado a mapas digitais, analise espacial, sensoriamento remoto e dados geograficos.'),
('geo-atuacao', 'Profissionais de GEO podem atuar com cartografia, planejamento urbano, meio ambiente, transporte, agricultura e sistemas de informacao geografica.'),
('curso-mb', 'MB e o curso de Meio Ambiente e Recursos Hidricos, com foco em sustentabilidade, gestao ambiental e preservacao dos recursos naturais.'),
('mb-mercado', 'A area permite atuar em empresas, orgaos publicos, consultorias ambientais, saneamento, licenciamento e projetos de conservacao.'),
('geral', 'Sobre qual assunto geral voce quer saber?'),
('geral-horario', 'O atendimento da unidade deve ser confirmado nos canais oficiais da Fatec Jacarei. Este prototipo usa informacoes simuladas.'),
('geral-secretaria', 'A secretaria academica auxilia com matricula, documentos, rematricula, historico escolar e declaracoes.'),
('geral-localizacao', 'A Fatec Jacarei fica em Jacarei, SP. Em uma versao futura, este item pode exibir mapa e rotas.');

-- INSERT chat flow options (label, from_node_id, to_node_id, display_order)
INSERT INTO chat_flow_options (label, from_node_id, to_node_id, display_order) VALUES
('Curso', 'inicio', 'curso', 0),
('Geral', 'inicio', 'geral', 1),
('DSM', 'curso', 'curso-dsm', 0),
('GEO', 'curso', 'curso-geo', 1),
('MB', 'curso', 'curso-mb', 2),
('Voltar para anterior', 'curso', 'inicio', 3),
('Voltar para o inicio', 'curso', 'inicio', 4),
('Grade curricular', 'curso-dsm', 'dsm-grade', 0),
('Duracao do curso', 'curso-dsm', 'dsm-duracao', 1),
('Voltar para cursos', 'curso-dsm', 'curso', 2),
('Voltar para o inicio', 'curso-dsm', 'inicio', 3),
('Voltar para DSM', 'dsm-grade', 'curso-dsm', 0),
('Voltar para cursos', 'dsm-grade', 'curso', 1),
('Voltar para o inicio', 'dsm-grade', 'inicio', 2),
('Voltar para DSM', 'dsm-duracao', 'curso-dsm', 0),
('Voltar para cursos', 'dsm-duracao', 'curso', 1),
('Voltar para o inicio', 'dsm-duracao', 'inicio', 2),
('Areas de atuacao', 'curso-geo', 'geo-atuacao', 0),
('Voltar para cursos', 'curso-geo', 'curso', 1),
('Voltar para o inicio', 'curso-geo', 'inicio', 2),
('Voltar para GEO', 'geo-atuacao', 'curso-geo', 0),
('Voltar para cursos', 'geo-atuacao', 'curso', 1),
('Voltar para o inicio', 'geo-atuacao', 'inicio', 2),
('Mercado de trabalho', 'curso-mb', 'mb-mercado', 0),
('Voltar para cursos', 'curso-mb', 'curso', 1),
('Voltar para o inicio', 'curso-mb', 'inicio', 2),
('Voltar para MB', 'mb-mercado', 'curso-mb', 0),
('Voltar para cursos', 'mb-mercado', 'curso', 1),
('Voltar para o inicio', 'mb-mercado', 'inicio', 2),
('Horario de atendimento', 'geral', 'geral-horario', 0),
('Secretaria academica', 'geral', 'geral-secretaria', 1),
('Localizacao', 'geral', 'geral-localizacao', 2),
('Voltar para o inicio', 'geral', 'inicio', 3),
('Voltar para geral', 'geral-horario', 'geral', 0),
('Voltar para o inicio', 'geral-horario', 'inicio', 1),
('Voltar para geral', 'geral-secretaria', 'geral', 0),
('Voltar para o inicio', 'geral-secretaria', 'inicio', 1),
('Voltar para geral', 'geral-localizacao', 'geral', 0),
('Voltar para o inicio', 'geral-localizacao', 'inicio', 1);
